import { test } from "node:test";
import assert from "node:assert/strict";
import {
  PALETTE,
  BAND_COLUMN_HEADERS,
  columnBandPrefix,
  bandSpans,
  bandColor,
  bandColorFromCell,
  bandSegments,
  md5IntMod,
} from "../js/lib/bandcolors.js";

// Golden expected colors for 305 canonical band names, generated by executing
// gui_version/viewer.py's real PALETTE + _band_color code verbatim (see
// /tmp/opencode/bandcolors_ref.py). Includes B1..B120, n1..n120, sampled
// B121..B296 / n121..n296, and specials (leading zeros, huge digit runs,
// non-ASCII, empty string) so the 128-bit md5 -> mod-40 reduction is proven
// exact, not just for small cases.
const GOLDEN = [
  ["B1", "#263238"], ["B2", "#283593"], ["B3", "#37474F"],
  ["B4", "#5D4037"], ["B5", "#1565C0"], ["B6", "#6D4C41"],
  ["B7", "#880E4F"], ["B8", "#880E4F"], ["B9", "#37474F"],
  ["B10", "#0277BD"], ["B11", "#6D4C41"], ["B12", "#004D40"],
  ["B13", "#4E342E"], ["B14", "#7B1FA2"], ["B15", "#8D6E63"],
  ["B16", "#8D6E63"], ["B17", "#827717"], ["B18", "#827717"],
  ["B19", "#4527A0"], ["B20", "#1565C0"], ["B21", "#1A237E"],
  ["B22", "#880E4F"], ["B23", "#6D4C41"], ["B24", "#795548"],
  ["B25", "#3949AB"], ["B26", "#1A237E"], ["B27", "#8E24AA"],
  ["B28", "#C2185B"], ["B29", "#00695C"], ["B30", "#283593"],
  ["B31", "#8D6E63"], ["B32", "#283593"], ["B33", "#303F9F"],
  ["B34", "#37474F"], ["B35", "#1B5E20"], ["B36", "#5F6368"],
  ["B37", "#33691E"], ["B38", "#880E4F"], ["B39", "#5D4037"],
  ["B40", "#00838F"], ["B41", "#AD1457"], ["B42", "#E64A19"],
  ["B43", "#E64A19"], ["B44", "#6A1B9A"], ["B45", "#00695C"],
  ["B46", "#5F6368"], ["B47", "#BF360C"], ["B48", "#BF360C"],
  ["B49", "#6A1B9A"], ["B50", "#795548"], ["B51", "#3949AB"],
  ["B52", "#6A1B9A"], ["B53", "#455A64"], ["B54", "#512DA8"],
  ["B55", "#2E7D32"], ["B56", "#1A237E"], ["B57", "#6D4C41"],
  ["B58", "#283593"], ["B59", "#0277BD"], ["B60", "#512DA8"],
  ["B61", "#AD1457"], ["B62", "#263238"], ["B63", "#00796B"],
  ["B64", "#9C27B0"], ["B65", "#004D40"], ["B66", "#C2185B"],
  ["B67", "#8D6E63"], ["B68", "#0D47A1"], ["B69", "#E64A19"],
  ["B70", "#3949AB"], ["B71", "#3949AB"], ["B72", "#004D40"],
  ["B73", "#880E4F"], ["B74", "#6D4C41"], ["B75", "#7B1FA2"],
  ["B76", "#33691E"], ["B77", "#827717"], ["B78", "#303F9F"],
  ["B79", "#00695C"], ["B80", "#0D47A1"], ["B81", "#8E24AA"],
  ["B82", "#00796B"], ["B83", "#1B5E20"], ["B84", "#827717"],
  ["B85", "#5F6368"], ["B86", "#B71C1C"], ["B87", "#3949AB"],
  ["B88", "#6A1B9A"], ["B89", "#9C27B0"], ["B90", "#7B1FA2"],
  ["B91", "#D32F2F"], ["B92", "#00695C"], ["B93", "#512DA8"],
  ["B94", "#00796B"], ["B95", "#00695C"], ["B96", "#827717"],
  ["B97", "#E64A19"], ["B98", "#6D4C41"], ["B99", "#0D47A1"],
  ["B100", "#004D40"], ["B101", "#6D4C41"], ["B102", "#5D4037"],
  ["B103", "#8E24AA"], ["B104", "#5D4037"], ["B105", "#1B5E20"],
  ["B106", "#283593"], ["B107", "#795548"], ["B108", "#9C27B0"],
  ["B109", "#1565C0"], ["B110", "#880E4F"], ["B111", "#00838F"],
  ["B112", "#283593"], ["B113", "#AD1457"], ["B114", "#006064"],
  ["B115", "#B71C1C"], ["B116", "#B71C1C"], ["B117", "#5F6368"],
  ["B118", "#1A237E"], ["B119", "#B71C1C"], ["B120", "#4527A0"],
  ["n1", "#004D40"], ["n2", "#0277BD"], ["n3", "#D84315"],
  ["n4", "#1A237E"], ["n5", "#00838F"], ["n6", "#6A1B9A"],
  ["n7", "#C2185B"], ["n8", "#00838F"], ["n9", "#880E4F"],
  ["n10", "#880E4F"], ["n11", "#37474F"], ["n12", "#8D6E63"],
  ["n13", "#37474F"], ["n14", "#01579B"], ["n15", "#8E24AA"],
  ["n16", "#B71C1C"], ["n17", "#6A1B9A"], ["n18", "#E64A19"],
  ["n19", "#880E4F"], ["n20", "#00695C"], ["n21", "#263238"],
  ["n22", "#01579B"], ["n23", "#2E7D32"], ["n24", "#4527A0"],
  ["n25", "#33691E"], ["n26", "#9C27B0"], ["n27", "#6D4C41"],
  ["n28", "#0D47A1"], ["n29", "#37474F"], ["n30", "#D84315"],
  ["n31", "#4E342E"], ["n32", "#303F9F"], ["n33", "#B71C1C"],
  ["n34", "#D84315"], ["n35", "#8D6E63"], ["n36", "#1565C0"],
  ["n37", "#7B1FA2"], ["n38", "#8D6E63"], ["n39", "#5D4037"],
  ["n40", "#1565C0"], ["n41", "#1565C0"], ["n42", "#3949AB"],
  ["n43", "#D84315"], ["n44", "#BF360C"], ["n45", "#0D47A1"],
  ["n46", "#6A1B9A"], ["n47", "#BF360C"], ["n48", "#4527A0"],
  ["n49", "#827717"], ["n50", "#D32F2F"], ["n51", "#1B5E20"],
  ["n52", "#5F6368"], ["n53", "#00695C"], ["n54", "#303F9F"],
  ["n55", "#00796B"], ["n56", "#0D47A1"], ["n57", "#283593"],
  ["n58", "#880E4F"], ["n59", "#1565C0"], ["n60", "#00796B"],
  ["n61", "#00695C"], ["n62", "#3949AB"], ["n63", "#6A1B9A"],
  ["n64", "#8D6E63"], ["n65", "#0277BD"], ["n66", "#D32F2F"],
  ["n67", "#7B1FA2"], ["n68", "#D32F2F"], ["n69", "#512DA8"],
  ["n70", "#00838F"], ["n71", "#303F9F"], ["n72", "#004D40"],
  ["n73", "#6A1B9A"], ["n74", "#6A1B9A"], ["n75", "#6D4C41"],
  ["n76", "#C2185B"], ["n77", "#880E4F"], ["n78", "#827717"],
  ["n79", "#006064"], ["n80", "#D84315"], ["n81", "#1B5E20"],
  ["n82", "#7B1FA2"], ["n83", "#00695C"], ["n84", "#2E7D32"],
  ["n85", "#795548"], ["n86", "#827717"], ["n87", "#D84315"],
  ["n88", "#BF360C"], ["n89", "#3949AB"], ["n90", "#455A64"],
  ["n91", "#5F6368"], ["n92", "#4527A0"], ["n93", "#33691E"],
  ["n94", "#1565C0"], ["n95", "#006064"], ["n96", "#1A237E"],
  ["n97", "#004D40"], ["n98", "#01579B"], ["n99", "#37474F"],
  ["n100", "#00695C"], ["n101", "#1A237E"], ["n102", "#B71C1C"],
  ["n103", "#0277BD"], ["n104", "#B71C1C"], ["n105", "#0D47A1"],
  ["n106", "#004D40"], ["n107", "#4E342E"], ["n108", "#AD1457"],
  ["n109", "#00796B"], ["n110", "#00838F"], ["n111", "#D84315"],
  ["n112", "#3949AB"], ["n113", "#8E24AA"], ["n114", "#5D4037"],
  ["n115", "#00796B"], ["n116", "#33691E"], ["n117", "#0277BD"],
  ["n118", "#00695C"], ["n119", "#37474F"], ["n120", "#E64A19"],
  ["B121", "#9C27B0"], ["n121", "#455A64"], ["B128", "#D84315"],
  ["n128", "#B71C1C"], ["B135", "#795548"], ["n135", "#01579B"],
  ["B142", "#5F6368"], ["n142", "#AD1457"], ["B149", "#BF360C"],
  ["n149", "#004D40"], ["B156", "#8D6E63"], ["n156", "#2E7D32"],
  ["B163", "#6A1B9A"], ["n163", "#455A64"], ["B170", "#2E7D32"],
  ["n170", "#455A64"], ["B177", "#006064"], ["n177", "#4E342E"],
  ["B184", "#E64A19"], ["n184", "#006064"], ["B191", "#827717"],
  ["n191", "#4527A0"], ["B198", "#303F9F"], ["n198", "#4E342E"],
  ["B205", "#0277BD"], ["n205", "#8D6E63"], ["B212", "#4527A0"],
  ["n212", "#33691E"], ["B219", "#263238"], ["n219", "#C2185B"],
  ["B226", "#795548"], ["n226", "#880E4F"], ["B233", "#AD1457"],
  ["n233", "#6A1B9A"], ["B240", "#AD1457"], ["n240", "#5F6368"],
  ["B247", "#D84315"], ["n247", "#C2185B"], ["B254", "#C2185B"],
  ["n254", "#795548"], ["B261", "#9C27B0"], ["n261", "#1A237E"],
  ["B268", "#4527A0"], ["n268", "#AD1457"], ["B275", "#5F6368"],
  ["n275", "#9C27B0"], ["B282", "#303F9F"], ["n282", "#827717"],
  ["B289", "#6D4C41"], ["n289", "#37474F"], ["B296", "#01579B"],
  ["n296", "#6A1B9A"], ["B0", "#00695C"], ["n0", "#6A1B9A"],
  ["B1000", "#00695C"], ["n99999", "#8E24AA"], ["n007", "#006064"],
  ["B123456789012345678901234567890", "#BF360C"], ["B", "#455A64"], ["n", "#33691E"],
  ["x", "#E64A19"], ["BΩ", "#00796B"], ["nÄ", "#1A237E"],
  ["", "#9C27B0"], ["B𝟎3", "#2E7D32"],
];

test("band colors match Tk viewer exactly", () => {
  assert.deepEqual(BAND_COLUMN_HEADERS, ["LTE DL", "LTE UL", "NR DL", "NR UL", "FR1 DL", "FR2 DL", "FR1 UL", "FR2 UL"]);
  assert.equal(bandColor("B3"), bandColorFromCell("B3C + B7A", "LTE DL")); // B3A/B3C share B3's color
  assert.equal(bandColor("B42") === bandColor("n42"), false);
  assert.equal(PALETTE.length, 40);
  assert.equal(bandColor("B3"), PALETTE[md5IntMod("B3", 40)]);
});

test("PALETTE is element-identical to viewer.py (order + hex strings)", () => {
  assert.deepEqual(PALETTE, [
    "#B71C1C", "#D32F2F", "#C2185B", "#AD1457", "#880E4F",
    "#7B1FA2", "#9C27B0", "#6A1B9A", "#512DA8", "#4527A0",
    "#3949AB", "#303F9F", "#283593", "#1A237E", "#1565C0",
    "#0D47A1", "#0277BD", "#01579B", "#00838F", "#006064",
    "#00796B", "#00695C", "#004D40", "#2E7D32", "#1B5E20",
    "#33691E", "#827717", "#8D6E63", "#795548", "#6D4C41",
    "#5D4037", "#4E342E", "#5F6368", "#455A64", "#37474F",
    "#263238", "#BF360C", "#D84315", "#E64A19", "#8E24AA",
  ]);
});

test("columnBandPrefix ports _column_band_prefix (substring, case-sensitive)", () => {
  assert.equal(columnBandPrefix("LTE DL"), "B");
  assert.equal(columnBandPrefix("LTE UL"), "B");
  assert.equal(columnBandPrefix("NR DL"), "n");
  assert.equal(columnBandPrefix("FR1 DL"), "n");
  assert.equal(columnBandPrefix("FR2 UL"), "n");
  assert.equal(columnBandPrefix("X LTE Y"), "B");
  assert.equal(columnBandPrefix("lte dl"), "n");
  assert.equal(columnBandPrefix("MIMO DL"), "n");
  assert.equal(columnBandPrefix(""), "n");
});

test("bandSpans prefixed vs plain tokens (viewer.py:49-66 semantics)", () => {
  assert.deepEqual(bandSpans("42E + 7A", "LTE DL"),
    [{ start: 0, end: 3, canonical: "B42" }, { start: 6, end: 8, canonical: "B7" }]);
  assert.deepEqual(bandSpans("78A + 41C", "NR DL"),
    [{ start: 0, end: 3, canonical: "n78" }, { start: 6, end: 9, canonical: "n41" }]);
  // _BAND_RE keeps the prefix AS WRITTEN: B3A is B3 even in an NR column.
  assert.deepEqual(bandSpans("B3A", "NR DL"), [{ start: 0, end: 3, canonical: "B3" }]);
  assert.deepEqual(bandSpans("n78", "LTE DL"), [{ start: 0, end: 3, canonical: "n78" }]);
  assert.deepEqual(bandSpans("B42G", "FR1 DL"), [{ start: 0, end: 4, canonical: "B42" }]);
  // "999Z" matches the plain regex (digits + one trailing letter), per Python.
  assert.deepEqual(bandSpans("999Z", "LTE DL"), [{ start: 0, end: 4, canonical: "B999" }]);
  assert.deepEqual(bandSpans("999Z", "NR DL"), [{ start: 0, end: 4, canonical: "n999" }]);
  assert.deepEqual(bandSpans("2 + 4", "FR1 UL"),
    [{ start: 0, end: 1, canonical: "n2" }, { start: 4, end: 5, canonical: "n4" }]);
  assert.deepEqual(bandSpans("1A + 1A", "FR2 DL"),
    [{ start: 0, end: 2, canonical: "n1" }, { start: 5, end: 7, canonical: "n1" }]);
  assert.deepEqual(bandSpans("n41D + n28A", "NR DL"),
    [{ start: 0, end: 4, canonical: "n41" }, { start: 7, end: 11, canonical: "n28" }]);
  assert.deepEqual(bandSpans("1 + 2 + 3", "NR UL"),
    [{ start: 0, end: 1, canonical: "n1" }, { start: 4, end: 5, canonical: "n2" }, { start: 8, end: 9, canonical: "n3" }]);
  assert.deepEqual(bandSpans("B66A + B2NONE", "LTE DL"), [{ start: 0, end: 4, canonical: "B66" }]);
});

test("bandSpans skips non-matching tokens but still advances offsets", () => {
  assert.deepEqual(bandSpans("XX + B3", "LTE DL"), [{ start: 5, end: 7, canonical: "B3" }]);
  assert.deepEqual(bandSpans("B3 + ", "LTE DL"), [{ start: 0, end: 2, canonical: "B3" }]);
  assert.deepEqual(bandSpans("42E + XX + 7A", "LTE DL"),
    [{ start: 0, end: 3, canonical: "B42" }, { start: 11, end: 13, canonical: "B7" }]);
  assert.deepEqual(bandSpans("8-", "LTE DL"), []);
  assert.deepEqual(bandSpans("b3", "LTE DL"), []);
  assert.deepEqual(bandSpans("B3AB", "LTE DL"), []);
  assert.deepEqual(bandSpans(" 42E", "LTE DL"), []);
  assert.deepEqual(bandSpans("42e", "LTE DL"), []);
  assert.deepEqual(bandSpans("FR1DL", "FR1 DL"), []);
  assert.deepEqual(bandSpans("LTE DL", "LTE DL"), []);
  assert.deepEqual(bandSpans("", "LTE DL"), []);
});

test("bandSpans non-band columns return [] (exact header membership)", () => {
  for (const [cell, header] of [["B3", "MIMO DL"], ["256", "SCS"], ["2 + 4", "DL (QAM)"], ["42E", "lte dl"], ["42E", "LTE"]]) {
    assert.deepEqual(bandSpans(cell, header), []);
  }
});

test("bandSpans Python str-regex parity: $-newline and Unicode Nd digits", () => {
  // Python '$' also matches just before a single trailing newline, and str \d
  // is Unicode category Nd; spans are measured in code points like len().
  assert.deepEqual(bandSpans("B3\n", "LTE DL"), [{ start: 0, end: 3, canonical: "B3" }]);
  assert.deepEqual(bandSpans("B3A\n", "LTE DL"), [{ start: 0, end: 4, canonical: "B3" }]);
  assert.deepEqual(bandSpans("B٤٢", "LTE DL"), [{ start: 0, end: 3, canonical: "B٤٢" }]);
  assert.deepEqual(bandSpans("B٣ + 5A", "LTE UL"),
    [{ start: 0, end: 2, canonical: "B٣" }, { start: 5, end: 7, canonical: "B5" }]);
  assert.deepEqual(bandSpans("𝟎3 + B1", "NR DL"),
    [{ start: 0, end: 2, canonical: "n𝟎3" }, { start: 5, end: 7, canonical: "B1" }]);
});

test("bandColorFromCell uses the first band token, null when none", () => {
  assert.equal(bandColorFromCell("B3C + B7A", "LTE DL"), bandColor("B3"));
  assert.equal(bandColorFromCell("XX + 7A", "LTE DL"), bandColor("B7"));
  assert.equal(bandColorFromCell("n41D + n28A", "NR DL"), bandColor("n41"));
  assert.equal(bandColorFromCell("8-", "LTE DL"), null);
  assert.equal(bandColorFromCell("B3", "MIMO DL"), null);
  assert.equal(bandColorFromCell("", "LTE DL"), null);
});

test("md5IntMod is exact int(md5(s.encode()).hexdigest(), 16) % m (Python-verified)", () => {
  assert.equal(md5IntMod("B3", 40), 34); // md5("B3") = 0c4ecd7b59ebc5b9f47974cb9845fd02
  assert.equal(md5IntMod("", 40), 6);
  assert.equal(md5IntMod("n78", 1024), 498);
  assert.equal(md5IntMod("BΩ", 40), 20); // utf-8 encoded like Python .encode()
  assert.equal(md5IntMod("𝟎3", 7), 4);
  assert.equal(md5IntMod("B3", 1), 0);
});

test("differential: 305 canonical colors match the Python viewer exactly", () => {
  assert.equal(GOLDEN.length, 305);
  const paletteSet = new Set(PALETTE);
  for (const [canonical, color] of GOLDEN) {
    assert.equal(bandColor(canonical), color, `bandColor(${JSON.stringify(canonical)})`);
    assert.ok(paletteSet.has(color), `${color} not in PALETTE`);
  }
});

test("bandSegments token-level helper for an HTML-table renderer", () => {
  assert.deepEqual(bandSegments("42E + XX + 7A", "LTE DL"), [
    { text: "42E", canonical: "B42" },
    { text: "XX", canonical: null },
    { text: "7A", canonical: "B7" },
  ]);
  assert.deepEqual(bandSegments("B3A", "NR DL"), [{ text: "B3A", canonical: "B3" }]);
  // Segments mirror cell.split(" + ") 1:1 (unparsable tokens keep canonical
  // null), so join(" + ") always reassembles the cell — including empty cells.
  assert.deepEqual(bandSegments("", "LTE DL"), [{ text: "", canonical: null }]);
  assert.deepEqual(bandSegments("B3", "MIMO DL"), []);
  for (const [cell, header] of [["42E + XX + 7A", "LTE DL"], ["B3C + B7A", "LTE DL"], ["8-", "LTE DL"]]) {
    assert.equal(bandSegments(cell, header).map((s) => s.text).join(" + "), cell);
  }
});
